[[headers]]
  for = "/*.js"
  [headers.values]
    "Content-Type" = "application/javascript"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    "Access-Control-Allow-Origin" = "*"
    "Content-Type" = "font/ttf"
    "Cache-Control" = "public, max-age=31536000, immutable"